### ISSUE TITLE
加入下拉刷新之后与向下拖拽冲突

### ISSUE THREAD

**Issue by jayceeok** [OCNYang/RecyclerViewEvent#5]
第一个item与第二个item交换位置的时候会触发下拉刷新怎么解决啊？

**Comment by OCNYang** [comment]
我用 SwipeRefreshLayout 测试了一下，没有发现有冲突的情况。你用的什么刷新控件，看看是不是刷新控件事件控制的有问题。

**Comment by jayceeok** [comment]
> 我用 SwipeRefreshLayout 测试了一下，没有发现有冲突的情况。你用的什么刷新控件，看看是不是刷新控件事件控制的有问题。

用的这个~TwinklingRefreshLayout

**Comment by OCNYang** [comment]
[直走](https://github.com/lcodecorex/TwinklingRefreshLayout/issues?utf8=%E2%9C%93&q=%E5%86%B2%E7%AA%81+)

**Comment by jayceeok** [comment]
> [直走](https://github.com/lcodecorex/TwinklingRefreshLayout/issues?utf8=%E2%9C%93&q=%E5%86%B2%E7%AA%81+)
Thanks♪(･ω･)ﾉ，我这边找到对应的方法了，之前只在拖动的时候用了setEnableRefresh（）这个方法，设为false，还是能拉下来，然后我在他控件里找到了另一个setEnableOverScroll（）方法，控制越界回弹的，拖动的时候把两个都设置为false就可以了，然后松开的时候再置为true。
